/*
 * File:    kinetis_flexcan.h
 * Purpose: Register and bit definitions
 */

#ifndef __KINETIS_FLEXCAN_H
#define __KINETIS_FLEXCAN_H

#include <stdint.h>

#define BITNUMBER(x) (1LU<<x)

/* FlexCAN module I/O Base Addresss */
#define                              FLEXCAN0_BASE (0x40024000LU)
#define                              FLEXCAN1_BASE (0x400A4000LU)

#define                             FLEXCANb_MCR(b) (*(volatile uint32_t*)(b))
#define                           FLEXCANb_CTRL1(b) (*(volatile uint32_t*)(b+4))
#define                        FLEXCANb_RXMGMASK(b) (*(volatile uint32_t*)(b+0x10))
#define                          FLEXCANb_IFLAG1(b) (*(volatile uint32_t*)(b+0x30))
#define                          FLEXCANb_IMASK1(b) (*(volatile uint32_t*)(b+0x28))
#define                        FLEXCANb_RXFGMASK(b) (*(volatile uint32_t*)(b+0x48))
#define                       FLEXCANb_MBn_CS(b, n) (*(volatile uint32_t*)(b+0x80+n*0x10))
#define                       FLEXCANb_MBn_ID(b, n) (*(volatile uint32_t*)(b+0x84+n*0x10))
#define                    FLEXCANb_MBn_WORD0(b, n) (*(volatile uint32_t*)(b+0x88+n*0x10))
#define                    FLEXCANb_MBn_WORD1(b, n) (*(volatile uint32_t*)(b+0x8C+n*0x10))
#define                    FLEXCANb_IDFLT_TAB(b, n) (*(volatile uint32_t*)(b+0xE0+(n*4)))
#define                      FLEXCANb_MB_MASK(b, n) (*(volatile uint32_t*)(b+0x880+(n*4)))
#define                            FLEXCANb_ESR1(b) (*(volatile uint32_t*)(b+0x20))
//typedef volatile uint32_t vuint32_t;

/*********************************************************************
 *
 * FlexCAN0 (FLEXCAN0)
 *
 *********************************************************************/

/* Register read/write macros */
#define                               FLEXCAN0_MCR (*(volatile uint32_t*)(FLEXCAN0_BASE))
#define                             FLEXCAN0_CTRL1 (*(volatile uint32_t*)(FLEXCAN0_BASE+4))
#define                             FLEXCAN0_TIMER (*(volatile uint32_t*)(FLEXCAN0_BASE+8))
#define                               FLEXCAN0_TCR (*(volatile uint32_t*)(FLEXCAN0_BASE+0x0C))
#define                          FLEXCAN0_RXMGMASK (*(volatile uint32_t*)(FLEXCAN0_BASE+0x10))
#define                          FLEXCAN0_RX14MASK (*(volatile uint32_t*)(FLEXCAN0_BASE+0x14))
#define                          FLEXCAN0_RX15MASK (*(volatile uint32_t*)(FLEXCAN0_BASE+0x18))
#define                               FLEXCAN0_ECR (*(volatile uint32_t*)(FLEXCAN0_BASE+0x1C))
#define                              FLEXCAN0_ESR1 (*(volatile uint32_t*)(FLEXCAN0_BASE+0x20))
#define                            FLEXCAN0_IMASK2 (*(volatile uint32_t*)(FLEXCAN0_BASE+0x24))
#define                            FLEXCAN0_IMASK1 (*(volatile uint32_t*)(FLEXCAN0_BASE+0x28))
#define                            FLEXCAN0_IFLAG2 (*(volatile uint32_t*)(FLEXCAN0_BASE+0x2C))
#define                            FLEXCAN0_IFLAG1 (*(volatile uint32_t*)(FLEXCAN0_BASE+0x30))
#define                             FLEXCAN0_CTRL2 (*(volatile uint32_t*)(FLEXCAN0_BASE+0x34))
#define                              FLEXCAN0_ESR2 (*(volatile uint32_t*)(FLEXCAN0_BASE+0x38))
#define                             FLEXCAN0_FUREQ (*(volatile uint32_t*)(FLEXCAN0_BASE+0x3C))
#define                             FLEXCAN0_FUACK (*(volatile uint32_t*)(FLEXCAN0_BASE+0x40))
#define                              FLEXCAN0_CRCR (*(volatile uint32_t*)(FLEXCAN0_BASE+0x44))
#define                          FLEXCAN0_RXFGMASK (*(volatile uint32_t*)(FLEXCAN0_BASE+0x48))
#define                             FLEXCAN0_RXFIR (*(volatile uint32_t*)(FLEXCAN0_BASE+0x4C))

#if defined(KINETISKE) 
#define                               FLEXCAN0_CBT (*(volatile uint32_t *)(FLEXCAN0_BASE+0x50))
#else
#define                              FLEXCAN0_DBG1 (*(volatile uint32_t*)(FLEXCAN0_BASE+0x58))
#define                              FLEXCAN0_DBG2 (*(volatile uint32_t*)(FLEXCAN0_BASE+0x5C))
#endif

#define                             FLEXCAN0_IMEUR FLEXCAN0_FUREQ
#define                              FLEXCAN0_LRFR FLEXCAN0_FUACK


/* Message Buffers */
#define                            FLEXCAN0_MB0_CS (*(volatile uint32_t*)(FLEXCAN0_BASE+0x80))
#define                            FLEXCAN0_MB0_ID (*(volatile uint32_t*)(FLEXCAN0_BASE+0x84))
#define                         FLEXCAN0_MB0_WORD0 (*(volatile uint32_t*)(FLEXCAN0_BASE+0x88))
#define                         FLEXCAN0_MB0_WORD1 (*(volatile uint32_t*)(FLEXCAN0_BASE+0x8C))

#define                         FLEXCAN0_MBn_CS(n) (*(volatile uint32_t*)(FLEXCAN0_BASE+0x80+n*0x10))
#define                         FLEXCAN0_MBn_ID(n) (*(volatile uint32_t*)(FLEXCAN0_BASE+0x84+n*0x10))
#define                      FLEXCAN0_MBn_WORD0(n) (*(volatile uint32_t*)(FLEXCAN0_BASE+0x88+n*0x10))
#define                      FLEXCAN0_MBn_WORD1(n) (*(volatile uint32_t*)(FLEXCAN0_BASE+0x8C+n*0x10))

/* Rx Individual Mask Registers */
#define                            FLEXCAN0_RXIMR0 (*(volatile uint32_t*)(FLEXCAN0_BASE+0x880))
#define                         FLEXCAN0_RXIMRn(n) (*(volatile uint32_t*)(FLEXCAN0_BASE+0x880+n*4))

/* Rx FIFO ID Filter Table Element 0 to 127 */
#define                        FLEXCAN0_IDFLT_TAB0 (*(volatile uint32_t*)(FLEXCAN0_BASE+0xE0))
#define                      FLEXCAN0_IDFLT_TAB(n) (*(volatile uint32_t*)(FLEXCAN0_BASE+0xE0+(n*4)))
//#define          FLEXCAN0_IDFLT_TAB(n) (*(volatile uint32_t*)(FLEXCAN0_BASE+0xE0+(n<<2)))

/* Memory Error Control Register */
#define                              FLEXCAN0_MECR *(volatile uint32_t*)(FLEXCAN0_BASE+0x3B70))

/* Error Injection Address Register */
#define                            FLEXCAN0_ERRIAR *(volatile uint32_t*)(FLEXCAN0_BASE+0x3B74))

/* Error Injection Data Pattern Register */
#define                           FLEXCAN0_ERRIDPR *(volatile uint32_t*)(FLEXCAN0_BASE+0x3B78))

/* Error Injection Parity Pattern Register */
#define                           FLEXCAN0_ERRIPPR *(volatile uint32_t*)(FLEXCAN0_BASE+0x3B7C))

/* Error Report Address Register */
#define                            FLEXCAN0_RERRAR *(volatile uint32_t*)(FLEXCAN0_BASE+0x3B80))

/* Error Report Data Register */
#define                            FLEXCAN0_RERRDR *(volatile uint32_t*)(FLEXCAN0_BASE+0x3B84))

/* Error Report Syndrome Register */
#define                          FLEXCAN0_RERRSYNR *(volatile uint32_t*)(FLEXCAN0_BASE+0x3B88))

/* Error Status Register */
#define                             FLEXCAN0_ERRSR *(volatile uint32_t*)(FLEXCAN0_BASE+0x3B8C))


/*********************************************************************
 *
 * FlexCAN1 (FLEXCAN1)
 *
 *********************************************************************/
/* Register read/write macros */
#define                               FLEXCAN1_MCR (*(volatile uint32_t*)(FLEXCAN1_BASE))
#define                             FLEXCAN1_CTRL1 (*(volatile uint32_t*)(FLEXCAN1_BASE+4))
#define                             FLEXCAN1_TIMER (*(volatile uint32_t*)(FLEXCAN1_BASE+8))
#define                               FLEXCAN1_TCR (*(volatile uint32_t*)(FLEXCAN1_BASE+0x0C))
#define                          FLEXCAN1_RXMGMASK (*(volatile uint32_t*)(FLEXCAN1_BASE+0x10))
#define                          FLEXCAN1_RX14MASK (*(volatile uint32_t*)(FLEXCAN1_BASE+0x14))
#define                          FLEXCAN1_RX15MASK (*(volatile uint32_t*)(FLEXCAN1_BASE+0x18))
#define                               FLEXCAN1_ECR (*(volatile uint32_t*)(FLEXCAN1_BASE+0x1C))
#define                              FLEXCAN1_ESR1 (*(volatile uint32_t*)(FLEXCAN1_BASE+0x20))
#define                            FLEXCAN1_IMASK2 (*(volatile uint32_t*)(FLEXCAN1_BASE+0x24))
#define                            FLEXCAN1_IMASK1 (*(volatile uint32_t*)(FLEXCAN1_BASE+0x28))
#define                            FLEXCAN1_IFLAG2 (*(volatile uint32_t*)(FLEXCAN1_BASE+0x2C))
#define                            FLEXCAN1_IFLAG1 (*(volatile uint32_t*)(FLEXCAN1_BASE+0x30))
#define                             FLEXCAN1_CTRL2 (*(volatile uint32_t*)(FLEXCAN1_BASE+0x34))
#define                              FLEXCAN1_ESR2 (*(volatile uint32_t*)(FLEXCAN1_BASE+0x38))
#define                             FLEXCAN1_FUREQ (*(volatile uint32_t*)(FLEXCAN1_BASE+0x3C))
#define                             FLEXCAN1_FUACK (*(volatile uint32_t*)(FLEXCAN1_BASE+0x40))
#define                              FLEXCAN1_CRCR (*(volatile uint32_t*)(FLEXCAN1_BASE+0x44))
#define                          FLEXCAN1_RXFGMASK (*(volatile uint32_t*)(FLEXCAN1_BASE+0x48))
#define                             FLEXCAN1_RXFIR (*(volatile uint32_t*)(FLEXCAN1_BASE+0x4C))
#define                              FLEXCAN1_DBG1 (*(volatile uint32_t*)(FLEXCAN1_BASE+0x58))
#define                              FLEXCAN1_DBG2 (*(volatile uint32_t*)(FLEXCAN1_BASE+0x5C))

#define                             FLEXCAN1_IMEUR FLEXCAN1_FUREQ
#define                              FLEXCAN1_LRFR FLEXCAN1_FUACK

/* Message Buffers */
#define                            FLEXCAN1_MB0_CS (*(volatile uint32_t*)(FLEXCAN1_BASE+0x80))
#define                            FLEXCAN1_MB0_ID (*(volatile uint32_t*)(FLEXCAN1_BASE+0x84))
#define                         FLEXCAN1_MB0_WORD0 (*(volatile uint32_t*)(FLEXCAN1_BASE+0x88))
#define                         FLEXCAN1_MB0_WORD1 (*(volatile uint32_t*)(FLEXCAN1_BASE+0x8C))

#define                         FLEXCAN1_MBn_CS(n) (*(volatile uint32_t*)(FLEXCAN1_BASE+0x80+n*0x10))
#define                         FLEXCAN1_MBn_ID(n) (*(volatile uint32_t*)(FLEXCAN1_BASE+0x84+n*0x10))
#define                      FLEXCAN1_MBn_WORD0(n) (*(volatile uint32_t*)(FLEXCAN1_BASE+0x88+n*0x10))
#define                      FLEXCAN1_MBn_WORD1(n) (*(volatile uint32_t*)(FLEXCAN1_BASE+0x8C+n*0x10))

/* Rx Individual Mask Registers */
#define                            FLEXCAN1_RXIMR0 (*(volatile uint32_t*)(FLEXCAN1_BASE+0x880))
#define                         FLEXCAN1_RXIMRn(n) (*(volatile uint32_t*)(FLEXCAN1_BASE+0x880+n*4))


/* Rx FIFO ID Filter Table Element 0 to 127 */
#define                        FLEXCAN1_IDFLT_TAB0 (*(volatile uint32_t*)(FLEXCAN1_BASE+0xE0))
#define                      FLEXCAN1_IDFLT_TAB(n) (*(volatile uint32_t*)(FLEXCAN1_BASE+0xE0+(n<<2)))

/* Memory Error Control Register */
#define                              FLEXCAN1_MECR *(volatile uint32_t*)(FLEXCAN1_BASE+0x7B70))

/* Error Injection Address Register */
#define                            FLEXCAN1_ERRIAR *(volatile uint32_t*)(FLEXCAN1_BASE+0x3B74))

/* Error Injection Data Pattern Register */
#define                           FLEXCAN1_ERRIDPR *(volatile uint32_t*)(FLEXCAN1_BASE+0x3B78))

/* Error Injection Parity Pattern Register */
#define                           FLEXCAN1_ERRIPPR *(volatile uint32_t*)(FLEXCAN1_BASE+0x3B7C))

/* Error Report Address Register */
#define                            FLEXCAN1_RERRAR *(volatile uint32_t*)(FLEXCAN1_BASE+0x3B80))

/* Error Report Data Register */
#define                            FLEXCAN1_RERRDR *(volatile uint32_t*)(FLEXCAN1_BASE+0x3B84))

/* Error Report Syndrome Register */
#define                          FLEXCAN1_RERRSYNR *(volatile uint32_t*)(FLEXCAN1_BASE+0x3B88))

/* Error Status Register */
#define                             FLEXCAN1_ERRSR *(volatile uint32_t*)(FLEXCAN1_BASE+0x3B8C))

/* Bit definitions and macros for FLEXCAN_MCR */
#define                       FLEXCAN_MCR_MAXMB(x) ((x)&0x0000007FLU))
#define                        FLEXCAN_MCR_IDAM(x) (((x)&0x00000003LU)<<8)
#define                     FLEXCAN_MCR_MAXMB_MASK (0x0000007FLU)
#define                      FLEXCAN_MCR_IDAM_MASK (0x00000300LU)
#define                    FLEXCAN_MCR_IDAM_BIT_NO (8)
#define                            FLEXCAN_MCR_AEN BITNUMBER(12)
#define                       FLEXCAN_MCR_LPRIO_EN BITNUMBER(13)
#define                           FLEXCAN_MCR_IRMQ BITNUMBER(16)
#define                        FLEXCAN_MCR_SRX_DIS BITNUMBER(17)
#define                           FLEXCAN_MCR_DOZE BITNUMBER(18)
#define                        FLEXCAN_MCR_WAK_SRC BITNUMBER(19)
#define                        FLEXCAN_MCR_LPM_ACK BITNUMBER(20)
#define                         FLEXCAN_MCR_WRN_EN BITNUMBER(21)
#define                        FLEXCAN_MCR_SLF_WAK BITNUMBER(22)
#define                           FLEXCAN_MCR_SUPV BITNUMBER(23)
#define                        FLEXCAN_MCR_FRZ_ACK BITNUMBER(24)
#define                       FLEXCAN_MCR_SOFT_RST BITNUMBER(25)
#define                        FLEXCAN_MCR_WAK_MSK BITNUMBER(26)
#define                        FLEXCAN_MCR_NOT_RDY BITNUMBER(27)
#define                           FLEXCAN_MCR_HALT BITNUMBER(28)
#define                            FLEXCAN_MCR_FEN BITNUMBER(29)
#define                            FLEXCAN_MCR_FRZ BITNUMBER(30)
#define                           FLEXCAN_MCR_MDIS BITNUMBER(31)

/* Bit definitions and macros for FLEXCAN_CTRL */
#define                    FLEXCAN_CTRL_PROPSEG(x) ((x)&0x00000007LU)
#define                           FLEXCAN_CTRL_LOM BITNUMBER(3)
#define                          FLEXCAN_CTRL_LBUF BITNUMBER(4)
#define                         FLEXCAN_CTRL_TSYNC BITNUMBER(5)
#define                      FLEXCAN_CTRL_BOFF_REC BITNUMBER(6)
#define                           FLEXCAN_CTRL_SMP BITNUMBER(7)
#define                      FLEXCAN_CTRL_RWRN_MSK BITNUMBER(10)
#define                      FLEXCAN_CTRL_TWRN_MSK BITNUMBER(11)
#define                           FLEXCAN_CTRL_LPB BITNUMBER(12)
#define                       FLEXCAN_CTRL_CLK_SRC BITNUMBER(13)
#define                       FLEXCAN_CTRL_ERR_MSK BITNUMBER(14)
#define                      FLEXCAN_CTRL_BOFF_MSK BITNUMBER(15)
#define                      FLEXCAN_CTRL_PSEG2(x) (((x)&0x00000007LU)<<16)
#define                      FLEXCAN_CTRL_PSEG1(x) (((x)&0x00000007LU)<<19)
#define                        FLEXCAN_CTRL_RJW(x) (((x)&0x00000003LU)<<22)
#define                    FLEXCAN_CTRL_PRESDIV(x) (((x)&0x000000FFLU)<<24)

/* Bit definitions and macros for FLEXCAN_CTRL2 */
#define                       FLEXCAN_CTRL2_IMEUEN (BITNUMBER(31))
#define                         FLEXCAN_CTRL2_RFFN (0x0F000000LU)
#define                  FLEXCAN_CTRL2_RFFN_BIT_NO (24)
#define                         FLEXCAN_CTRL2_TASD (0x00F80000LU)
#define                  FLEXCAN_CTRL2_TASD_BIT_NO (19)
#define                          FLEXCAN_CTRL2_MRP (BITNUMBER(18))
#define                          FLEXCAN_CTRL2_RRS (BITNUMBER(17))
#define                        FLEXCAN_CTRL2_EACEN (BITNUMBER(16))
#define                       FLEXCAN_CTRL2_MUMASK (BITNUMBER(1))
#define                       FLEXCAN_CTRL2_FUMASK (BITNUMBER(0))
#define                    FLEXCAN_CTRL2_LOSTRLMSK (BITNUMBER(2))
#define                    FLEXCAN_CTRL2_LOSTRMMSK (BITNUMBER(1))
#define                     FLEXCAN_CTRL2_IMEUMASK (BITNUMBER(0))
#define               FLEXCAN_set_rffn(ctrl2,rffn) ctrl2 = ((ctrl2) & ~FLEXCAN_CTRL2_RFFN) | ((rffn & 0xF)<<FLEXCAN_CTRL2_RFFN_BIT_NO)


/* Bit definitions and macros for FLEXCAN_TIMER */
#define                     FLEXCAN_TIMER_TIMER(x) ((x)&0x0000FFFFLU)

/* Bit definitions and macros for FLEXCAN_TCR */
#define                         FLEXCAN_TCR_DSCACK BITNUMBER(8)
#define                        FLEXCAN_TCR_BIT_CLS BITNUMBER(9)
#define                            FLEXCAN_TCR_TRD BITNUMBER(10)

/* Bit definitions and macros for FLEXCAN_RXGMASK */
#define                        FLEXCAN_RXGMASK_MI0 BITNUMBER(0)
#define                        FLEXCAN_RXGMASK_MI1 BITNUMBER(1)
#define                        FLEXCAN_RXGMASK_MI2 BITNUMBER(2)
#define                        FLEXCAN_RXGMASK_MI3 BITNUMBER(3)
#define                        FLEXCAN_RXGMASK_MI4 BITNUMBER(4)
#define                        FLEXCAN_RXGMASK_MI5 BITNUMBER(5)
#define                        FLEXCAN_RXGMASK_MI6 BITNUMBER(6)
#define                        FLEXCAN_RXGMASK_MI7 BITNUMBER(7)
#define                        FLEXCAN_RXGMASK_MI8 BITNUMBER(8)
#define                        FLEXCAN_RXGMASK_MI9 BITNUMBER(9)
#define                       FLEXCAN_RXGMASK_MI10 BITNUMBER(10)
#define                       FLEXCAN_RXGMASK_MI11 BITNUMBER(11)
#define                       FLEXCAN_RXGMASK_MI12 BITNUMBER(12)
#define                       FLEXCAN_RXGMASK_MI13 BITNUMBER(13)
#define                       FLEXCAN_RXGMASK_MI14 BITNUMBER(14)
#define                       FLEXCAN_RXGMASK_MI15 BITNUMBER(15)
#define                       FLEXCAN_RXGMASK_MI16 BITNUMBER(16)
#define                       FLEXCAN_RXGMASK_MI17 BITNUMBER(17)
#define                       FLEXCAN_RXGMASK_MI18 BITNUMBER(18)
#define                       FLEXCAN_RXGMASK_MI19 BITNUMBER(19)
#define                       FLEXCAN_RXGMASK_MI20 BITNUMBER(20)
#define                       FLEXCAN_RXGMASK_MI21 BITNUMBER(21)
#define                       FLEXCAN_RXGMASK_MI22 BITNUMBER(22)
#define                       FLEXCAN_RXGMASK_MI23 BITNUMBER(23)
#define                       FLEXCAN_RXGMASK_MI24 BITNUMBER(24)
#define                       FLEXCAN_RXGMASK_MI25 BITNUMBER(25)
#define                       FLEXCAN_RXGMASK_MI26 BITNUMBER(26)
#define                       FLEXCAN_RXGMASK_MI27 BITNUMBER(27)
#define                       FLEXCAN_RXGMASK_MI28 BITNUMBER(28)
#define                       FLEXCAN_RXGMASK_MI29 BITNUMBER(29)
#define                       FLEXCAN_RXGMASK_MI30 BITNUMBER(30)
#define                       FLEXCAN_RXGMASK_MI31 BITNUMBER(31)

/* Bit definitions and macros for FLEXCAN_RX14MASK */
#define                       FLEXCAN_RX14MASK_MI0 BITNUMBER(0)
#define                       FLEXCAN_RX14MASK_MI1 BITNUMBER(1)
#define                       FLEXCAN_RX14MASK_MI2 BITNUMBER(2)
#define                       FLEXCAN_RX14MASK_MI3 BITNUMBER(3)
#define                       FLEXCAN_RX14MASK_MI4 BITNUMBER(4)
#define                       FLEXCAN_RX14MASK_MI5 BITNUMBER(5)
#define                       FLEXCAN_RX14MASK_MI6 BITNUMBER(6)
#define                       FLEXCAN_RX14MASK_MI7 BITNUMBER(7)
#define                       FLEXCAN_RX14MASK_MI8 BITNUMBER(8)
#define                       FLEXCAN_RX14MASK_MI9 BITNUMBER(9)
#define                      FLEXCAN_RX14MASK_MI10 BITNUMBER(10)
#define                      FLEXCAN_RX14MASK_MI11 BITNUMBER(11)
#define                      FLEXCAN_RX14MASK_MI12 BITNUMBER(12)
#define                      FLEXCAN_RX14MASK_MI13 BITNUMBER(13)
#define                      FLEXCAN_RX14MASK_MI14 BITNUMBER(14)
#define                      FLEXCAN_RX14MASK_MI15 BITNUMBER(15)
#define                      FLEXCAN_RX14MASK_MI16 BITNUMBER(16)
#define                      FLEXCAN_RX14MASK_MI17 BITNUMBER(17)
#define                      FLEXCAN_RX14MASK_MI18 BITNUMBER(18)
#define                      FLEXCAN_RX14MASK_MI19 BITNUMBER(19)
#define                      FLEXCAN_RX14MASK_MI20 BITNUMBER(20)
#define                      FLEXCAN_RX14MASK_MI21 BITNUMBER(21)
#define                      FLEXCAN_RX14MASK_MI22 BITNUMBER(22)
#define                      FLEXCAN_RX14MASK_MI23 BITNUMBER(23)
#define                      FLEXCAN_RX14MASK_MI24 BITNUMBER(24)
#define                      FLEXCAN_RX14MASK_MI25 BITNUMBER(25)
#define                      FLEXCAN_RX14MASK_MI26 BITNUMBER(26)
#define                      FLEXCAN_RX14MASK_MI27 BITNUMBER(27)
#define                      FLEXCAN_RX14MASK_MI28 BITNUMBER(28)
#define                      FLEXCAN_RX14MASK_MI29 BITNUMBER(29)
#define                      FLEXCAN_RX14MASK_MI30 BITNUMBER(30)
#define                      FLEXCAN_RX14MASK_MI31 BITNUMBER(31)

/* Bit definitions and macros for FLEXCAN_RX15MASK */
#define                       FLEXCAN_RX15MASK_MI0 BITNUMBER(0)
#define                       FLEXCAN_RX15MASK_MI1 BITNUMBER(1)
#define                       FLEXCAN_RX15MASK_MI2 BITNUMBER(2)
#define                       FLEXCAN_RX15MASK_MI3 BITNUMBER(3)
#define                       FLEXCAN_RX15MASK_MI4 BITNUMBER(4)
#define                       FLEXCAN_RX15MASK_MI5 BITNUMBER(5)
#define                       FLEXCAN_RX15MASK_MI6 BITNUMBER(6)
#define                       FLEXCAN_RX15MASK_MI7 BITNUMBER(7)
#define                       FLEXCAN_RX15MASK_MI8 BITNUMBER(8)
#define                       FLEXCAN_RX15MASK_MI9 BITNUMBER(9)
#define                      FLEXCAN_RX15MASK_MI10 BITNUMBER(10)
#define                      FLEXCAN_RX15MASK_MI11 BITNUMBER(11)
#define                      FLEXCAN_RX15MASK_MI12 BITNUMBER(12)
#define                      FLEXCAN_RX15MASK_MI13 BITNUMBER(13)
#define                      FLEXCAN_RX15MASK_MI14 BITNUMBER(14)
#define                      FLEXCAN_RX15MASK_MI15 BITNUMBER(15)
#define                      FLEXCAN_RX15MASK_MI16 BITNUMBER(16)
#define                      FLEXCAN_RX15MASK_MI17 BITNUMBER(17)
#define                      FLEXCAN_RX15MASK_MI18 BITNUMBER(18)
#define                      FLEXCAN_RX15MASK_MI19 BITNUMBER(19)
#define                      FLEXCAN_RX15MASK_MI20 BITNUMBER(20)
#define                      FLEXCAN_RX15MASK_MI21 BITNUMBER(21)
#define                      FLEXCAN_RX15MASK_MI22 BITNUMBER(22)
#define                      FLEXCAN_RX15MASK_MI23 BITNUMBER(23)
#define                      FLEXCAN_RX15MASK_MI24 BITNUMBER(24)
#define                      FLEXCAN_RX15MASK_MI25 BITNUMBER(25)
#define                      FLEXCAN_RX15MASK_MI26 BITNUMBER(26)
#define                      FLEXCAN_RX15MASK_MI27 BITNUMBER(27)
#define                      FLEXCAN_RX15MASK_MI28 BITNUMBER(28)
#define                      FLEXCAN_RX15MASK_MI29 BITNUMBER(29)
#define                      FLEXCAN_RX15MASK_MI30 BITNUMBER(30)
#define                      FLEXCAN_RX15MASK_MI31 BITNUMBER(31)

/* Bit definitions and macros for FLEXCAN_ECR */
#define              FLEXCAN_ECR_TX_ERR_COUNTER(x) ((x)&0x000000FFLU))
#define              FLEXCAN_ECR_RX_ERR_COUNTER(x) (((x)&0x000000FFLU)<<8)

/* Bit definitions and macros for FLEXCAN_ESR1 */
#define                        FLEXCAN_ESR_WAK_INT BITNUMBER(0)
#define                        FLEXCAN_ESR_ERR_INT BITNUMBER(1)
#define                       FLEXCAN_ESR_BOFF_INT BITNUMBER(2)
#define                             FLEXCAN_ESR_RX BITNUMBER(3)
#define                    FLEXCAN_ESR_FLT_CONF(x) (((x)&0x00000003LU)<<4)
#define                  FLEXCAN_ESR_FLT_CONF_MASK (0x00000030LU)
#define                             FLEXCAN_ESR_TX BITNUMBER(6)
#define                           FLEXCAN_ESR_IDLE BITNUMBER(7)
#define                         FLEXCAN_ESR_RX_WRN BITNUMBER(8)
#define                         FLEXCAN_ESR_TX_WRN BITNUMBER(9)
#define                        FLEXCAN_ESR_STF_ERR BITNUMBER(10)
#define                        FLEXCAN_ESR_FRM_ERR BITNUMBER(11)
#define                        FLEXCAN_ESR_CRC_ERR BITNUMBER(12)
#define                        FLEXCAN_ESR_ACK_ERR BITNUMBER(13)
#define                       FLEXCAN_ESR_BIT0_ERR BITNUMBER(14)
#define                       FLEXCAN_ESR_BIT1_ERR BITNUMBER(15)
#define                       FLEXCAN_ESR_RWRN_INT BITNUMBER(16)
#define                       FLEXCAN_ESR_TWRN_INT BITNUMBER(17)
#define            FLEXCAN_ESR_get_fault_code(esr) (((esr) & FLEXCAN_ESR_FLT_CONF_MASK)>>4)
#define                           CAN_ERROR_ACTIVE 0
#define                          CAN_ERROR_PASSIVE 1
#define                          CAN_ERROR_BUS_OFF 2

/* Bit definition for FLEXCAN_ESR2 */
#define                            FLEXCAN_ESR2_IMB BITNUMBER(13)
#define                            FLEXCAN_ESR2_VPS BITNUMBER(14)
#define                            FLEXCAN_ESR2_LTM (0x007F0000LU)
#define                     FLEXCAN_ESR2_LTM_BIT_NO (16)
#define                        FLEXCAN_ESR2_LOSTRLF BITNUMBER(2)
#define                        FLEXCAN_ESR2_LOSTRMF BITNUMBER(1)
#define                          FLEXCAN_ESR2_IMEUF BITNUMBER(0)
#define                 FLEXCAN_get_LTM(esr2_value) (((esr2_value) & (FLEXCAN_ESR2_LTM))>>(FLEXCAN_ESR2_LTM_BIT_NO))

/* Bit definitions and macros for FLEXCAN_IMASK1 */
#define                        FLEXCAN_IMASK1_BUF0M BITNUMBER(0)
#define                        FLEXCAN_IMASK1_BUF1M BITNUMBER(1)
#define                        FLEXCAN_IMASK1_BUF2M BITNUMBER(2)
#define                        FLEXCAN_IMASK1_BUF3M BITNUMBER(3)
#define                        FLEXCAN_IMASK1_BUF4M BITNUMBER(4)
#define                        FLEXCAN_IMASK1_BUF5M BITNUMBER(5)
#define                        FLEXCAN_IMASK1_BUF6M BITNUMBER(6)
#define                        FLEXCAN_IMASK1_BUF7M BITNUMBER(7)
#define                        FLEXCAN_IMASK1_BUF8M BITNUMBER(8)
#define                        FLEXCAN_IMASK1_BUF9M BITNUMBER(9)
#define                       FLEXCAN_IMASK1_BUF10M BITNUMBER(10)
#define                       FLEXCAN_IMASK1_BUF11M BITNUMBER(11)
#define                       FLEXCAN_IMASK1_BUF12M BITNUMBER(12)
#define                       FLEXCAN_IMASK1_BUF13M BITNUMBER(13)
#define                       FLEXCAN_IMASK1_BUF14M BITNUMBER(14)
#define                       FLEXCAN_IMASK1_BUF15M BITNUMBER(15)
#define                       FLEXCAN_IMASK1_BUF16M BITNUMBER(16)
#define                       FLEXCAN_IMASK1_BUF17M BITNUMBER(17)
#define                       FLEXCAN_IMASK1_BUF18M BITNUMBER(18)
#define                       FLEXCAN_IMASK1_BUF19M BITNUMBER(19)
#define                       FLEXCAN_IMASK1_BUF20M BITNUMBER(20)
#define                       FLEXCAN_IMASK1_BUF21M BITNUMBER(21)
#define                       FLEXCAN_IMASK1_BUF22M BITNUMBER(22)
#define                       FLEXCAN_IMASK1_BUF23M BITNUMBER(23)
#define                       FLEXCAN_IMASK1_BUF24M BITNUMBER(24)
#define                       FLEXCAN_IMASK1_BUF25M BITNUMBER(25)
#define                       FLEXCAN_IMASK1_BUF26M BITNUMBER(26)
#define                       FLEXCAN_IMASK1_BUF27M BITNUMBER(27)
#define                       FLEXCAN_IMASK1_BUF28M BITNUMBER(28)
#define                       FLEXCAN_IMASK1_BUF29M BITNUMBER(29)
#define                       FLEXCAN_IMASK1_BUF30M BITNUMBER(30)
#define                       FLEXCAN_IMASK1_BUF31M BITNUMBER(31)

/* Bit definitions and macros for FLEXCAN_IFLAG1 */
#define                        FLEXCAN_IFLAG1_BUF0I BITNUMBER(0)
#define                        FLEXCAN_IFLAG1_BUF1I BITNUMBER(1)
#define                        FLEXCAN_IFLAG1_BUF2I BITNUMBER(2)
#define                        FLEXCAN_IFLAG1_BUF3I BITNUMBER(3)
#define                        FLEXCAN_IFLAG1_BUF4I BITNUMBER(4)
#define                        FLEXCAN_IFLAG1_BUF5I BITNUMBER(5)
#define                        FLEXCAN_IFLAG1_BUF6I BITNUMBER(6)
#define                        FLEXCAN_IFLAG1_BUF7I BITNUMBER(7)
#define                        FLEXCAN_IFLAG1_BUF8I BITNUMBER(8)
#define                        FLEXCAN_IFLAG1_BUF9I BITNUMBER(9)
#define                       FLEXCAN_IFLAG1_BUF10I BITNUMBER(10)
#define                       FLEXCAN_IFLAG1_BUF11I BITNUMBER(11)
#define                       FLEXCAN_IFLAG1_BUF12I BITNUMBER(12)
#define                       FLEXCAN_IFLAG1_BUF13I BITNUMBER(13)
#define                       FLEXCAN_IFLAG1_BUF14I BITNUMBER(14)
#define                       FLEXCAN_IFLAG1_BUF15I BITNUMBER(15)
#define                       FLEXCAN_IFLAG1_BUF16I BITNUMBER(16)
#define                       FLEXCAN_IFLAG1_BUF17I BITNUMBER(17)
#define                       FLEXCAN_IFLAG1_BUF18I BITNUMBER(18)
#define                       FLEXCAN_IFLAG1_BUF19I BITNUMBER(19)
#define                       FLEXCAN_IFLAG1_BUF20I BITNUMBER(20)
#define                       FLEXCAN_IFLAG1_BUF21I BITNUMBER(21)
#define                       FLEXCAN_IFLAG1_BUF22I BITNUMBER(22)
#define                       FLEXCAN_IFLAG1_BUF23I BITNUMBER(23)
#define                       FLEXCAN_IFLAG1_BUF24I BITNUMBER(24)
#define                       FLEXCAN_IFLAG1_BUF25I BITNUMBER(25)
#define                       FLEXCAN_IFLAG1_BUF26I BITNUMBER(26)
#define                       FLEXCAN_IFLAG1_BUF27I BITNUMBER(27)
#define                       FLEXCAN_IFLAG1_BUF28I BITNUMBER(28)
#define                       FLEXCAN_IFLAG1_BUF29I BITNUMBER(29)
#define                       FLEXCAN_IFLAG1_BUF30I BITNUMBER(30)
#define                       FLEXCAN_IFLAG1_BUF31I BITNUMBER(31)

/* Bit definitions and macros for FLEXCAN_MB_CS */
#define                  FLEXCAN_MB_CS_TIMESTAMP(x) ((x)&0x0000FFFFLU)
#define                FLEXCAN_MB_CS_TIMESTAMP_MASK (0x0000FFFFLU)
#define                     FLEXCAN_MB_CS_LENGTH(x) (((x)&0x0000000FLU)<<16)
#define                           FLEXCAN_MB_CS_RTR BITNUMBER(20)
#define                           FLEXCAN_MB_CS_IDE BITNUMBER(21)
#define                           FLEXCAN_MB_CS_SRR BITNUMBER(22)
#define                       FLEXCAN_MB_CS_CODE(x) (((x)&0x0000000FLU)<<24)
#define                     FLEXCAN_MB_CS_CODE_MASK (0x0F000000LU)
#define                      FLEXCAN_MB_CS_DLC_MASK (0x000F0000LU)
#define                 FLEXCAN_MB_CODE_RX_INACTIVE (0)
#define                    FLEXCAN_MB_CODE_RX_EMPTY (4)
#define                     FLEXCAN_MB_CODE_RX_FULL (2)
#define                  FLEXCAN_MB_CODE_RX_OVERRUN (6)
#define                     FLEXCAN_MB_CODE_RX_BUSY (1)

#define                    FLEXCAN_MB_CS_IDE_BIT_NO (21)
#define                    FLEXCAN_MB_CS_RTR_BIT_NO (20)
#define                    FLEXCAN_MB_CS_DLC_BIT_NO (16)

#define                 FLEXCAN_MB_CODE_TX_INACTIVE (8)
#define                    FLEXCAN_MB_CODE_TX_ABORT (9)
#define                     FLEXCAN_MB_CODE_TX_ONCE (0x0C)
#define                 FLEXCAN_MB_CODE_TX_RESPONSE (0x0A)
#define           FLEXCAN_MB_CODE_TX_RESPONSE_TEMPO (0x0E)
#define                        FLEXCAN_get_code(cs) (((cs) & FLEXCAN_MB_CS_CODE_MASK)>>24)
#define                      FLEXCAN_get_length(cs) (((cs) & FLEXCAN_MB_CS_DLC_MASK)>>16)
#define                   FLEXCAN_get_timestamp(cs) (((cs) & FLEXCAN_MB_CS_TIMESTAMP_MASK)>>0)

/* Bit definitions and macros for FLEXCAN_MB_ID */
#define                     FLEXCAN_MB_ID_STD_MASK  (0x1FFC0000LU)
#define                     FLEXCAN_MB_ID_EXT_MASK  (0x1FFFFFFFLU)
#define                      FLEXCAN_MB_ID_IDEXT(x) ((x)&0x0003FFFFLU)
#define                      FLEXCAN_MB_ID_IDSTD(x) (((x)&0x000007FFLU)<<18)
#define                       FLEXCAN_MB_ID_PRIO(x) (((x)&0x00000007LU)<<29)
#define                   FLEXCAN_MB_ID_PRIO_BIT_NO (29)
#define                    FLEXCAN_MB_ID_STD_BIT_NO (18)
#define                    FLEXCAN_MB_ID_EXT_BIT_NO (0)


/* Bit definitions and macros for FLEXCAN_MB_WORD0 */
#define                   FLEXCAN_MB_WORD0_DATA3(x) ((x)&0x000000FFLU)
#define                   FLEXCAN_MB_WORD0_DATA2(x) (((x)&0x000000FFLU)<<8)
#define                   FLEXCAN_MB_WORD0_DATA1(x) (((x)&0x000000FFLU)<<16)
#define                   FLEXCAN_MB_WORD0_DATA0(x) (((x)&0x000000FFLU)<<24)

/* Bit definitions and macros for FLEXCAN_MB_WORD1 */
#define                   FLEXCAN_MB_WORD1_DATA7(x) ((x)&0x000000FFLU)
#define                   FLEXCAN_MB_WORD1_DATA6(x) (((x)&0x000000FFLU)<<8)
#define                   FLEXCAN_MB_WORD1_DATA5(x) (((x)&0x000000FFLU)<<16)
#define                   FLEXCAN_MB_WORD1_DATA4(x) (((x)&0x000000FFLU)<<24)

/* Bit definitions and macros for FLEXCAN_RXIMR0 */
#define                          FLEXCAN_RXIMR0_MI0 BITNUMBER(0)
#define                          FLEXCAN_RXIMR0_MI1 BITNUMBER(1)
#define                          FLEXCAN_RXIMR0_MI2 BITNUMBER(2)
#define                          FLEXCAN_RXIMR0_MI3 BITNUMBER(3)
#define                          FLEXCAN_RXIMR0_MI4 BITNUMBER(4)
#define                          FLEXCAN_RXIMR0_MI5 BITNUMBER(5)
#define                          FLEXCAN_RXIMR0_MI6 BITNUMBER(6)
#define                          FLEXCAN_RXIMR0_MI7 BITNUMBER(7)
#define                          FLEXCAN_RXIMR0_MI8 BITNUMBER(8)
#define                          FLEXCAN_RXIMR0_MI9 BITNUMBER(9)
#define                         FLEXCAN_RXIMR0_MI10 BITNUMBER(10)
#define                         FLEXCAN_RXIMR0_MI11 BITNUMBER(11)
#define                         FLEXCAN_RXIMR0_MI12 BITNUMBER(12)
#define                         FLEXCAN_RXIMR0_MI13 BITNUMBER(13)
#define                         FLEXCAN_RXIMR0_MI14 BITNUMBER(14)
#define                         FLEXCAN_RXIMR0_MI15 BITNUMBER(15)
#define                         FLEXCAN_RXIMR0_MI16 BITNUMBER(16)
#define                         FLEXCAN_RXIMR0_MI17 BITNUMBER(17)
#define                         FLEXCAN_RXIMR0_MI18 BITNUMBER(18)
#define                         FLEXCAN_RXIMR0_MI19 BITNUMBER(19)
#define                         FLEXCAN_RXIMR0_MI20 BITNUMBER(20)
#define                         FLEXCAN_RXIMR0_MI21 BITNUMBER(21)
#define                         FLEXCAN_RXIMR0_MI22 BITNUMBER(22)
#define                         FLEXCAN_RXIMR0_MI23 BITNUMBER(23)
#define                         FLEXCAN_RXIMR0_MI24 BITNUMBER(24)
#define                         FLEXCAN_RXIMR0_MI25 BITNUMBER(25)
#define                         FLEXCAN_RXIMR0_MI26 BITNUMBER(26)
#define                         FLEXCAN_RXIMR0_MI27 BITNUMBER(27)
#define                         FLEXCAN_RXIMR0_MI28 BITNUMBER(28)
#define                         FLEXCAN_RXIMR0_MI29 BITNUMBER(29)
#define                         FLEXCAN_RXIMR0_MI30 BITNUMBER(30)
#define                         FLEXCAN_RXIMR0_MI31 BITNUMBER(31)

/* Bit definitions and macros for FLEXCAN_RXIMR1 */
#define                          FLEXCAN_RXIMR1_MI0 BITNUMBER(0)
#define                          FLEXCAN_RXIMR1_MI1 BITNUMBER(1)
#define                          FLEXCAN_RXIMR1_MI2 BITNUMBER(2)
#define                          FLEXCAN_RXIMR1_MI3 BITNUMBER(3)
#define                          FLEXCAN_RXIMR1_MI4 BITNUMBER(4)
#define                          FLEXCAN_RXIMR1_MI5 BITNUMBER(5)
#define                          FLEXCAN_RXIMR1_MI6 BITNUMBER(6)
#define                          FLEXCAN_RXIMR1_MI7 BITNUMBER(7)
#define                          FLEXCAN_RXIMR1_MI8 BITNUMBER(8)
#define                          FLEXCAN_RXIMR1_MI9 BITNUMBER(9)
#define                         FLEXCAN_RXIMR1_MI10 BITNUMBER(10)
#define                         FLEXCAN_RXIMR1_MI11 BITNUMBER(11)
#define                         FLEXCAN_RXIMR1_MI12 BITNUMBER(12)
#define                         FLEXCAN_RXIMR1_MI13 BITNUMBER(13)
#define                         FLEXCAN_RXIMR1_MI14 BITNUMBER(14)
#define                         FLEXCAN_RXIMR1_MI15 BITNUMBER(15)
#define                         FLEXCAN_RXIMR1_MI16 BITNUMBER(16)
#define                         FLEXCAN_RXIMR1_MI17 BITNUMBER(17)
#define                         FLEXCAN_RXIMR1_MI18 BITNUMBER(18)
#define                         FLEXCAN_RXIMR1_MI19 BITNUMBER(19)
#define                         FLEXCAN_RXIMR1_MI20 BITNUMBER(20)
#define                         FLEXCAN_RXIMR1_MI21 BITNUMBER(21)
#define                         FLEXCAN_RXIMR1_MI22 BITNUMBER(22)
#define                         FLEXCAN_RXIMR1_MI23 BITNUMBER(23)
#define                         FLEXCAN_RXIMR1_MI24 BITNUMBER(24)
#define                         FLEXCAN_RXIMR1_MI25 BITNUMBER(25)
#define                         FLEXCAN_RXIMR1_MI26 BITNUMBER(26)
#define                         FLEXCAN_RXIMR1_MI27 BITNUMBER(27)
#define                         FLEXCAN_RXIMR1_MI28 BITNUMBER(28)
#define                         FLEXCAN_RXIMR1_MI29 BITNUMBER(29)
#define                         FLEXCAN_RXIMR1_MI30 BITNUMBER(30)
#define                         FLEXCAN_RXIMR1_MI31 BITNUMBER(31)

/* Bit definitions and macros for FLEXCAN_RXIMR2 */
#define                          FLEXCAN_RXIMR2_MI0 BITNUMBER(0)
#define                          FLEXCAN_RXIMR2_MI1 BITNUMBER(1)
#define                          FLEXCAN_RXIMR2_MI2 BITNUMBER(2)
#define                          FLEXCAN_RXIMR2_MI3 BITNUMBER(3)
#define                          FLEXCAN_RXIMR2_MI4 BITNUMBER(4)
#define                          FLEXCAN_RXIMR2_MI5 BITNUMBER(5)
#define                          FLEXCAN_RXIMR2_MI6 BITNUMBER(6)
#define                          FLEXCAN_RXIMR2_MI7 BITNUMBER(7)
#define                          FLEXCAN_RXIMR2_MI8 BITNUMBER(8)
#define                          FLEXCAN_RXIMR2_MI9 BITNUMBER(9)
#define                         FLEXCAN_RXIMR2_MI10 BITNUMBER(10)
#define                         FLEXCAN_RXIMR2_MI11 BITNUMBER(11)
#define                         FLEXCAN_RXIMR2_MI12 BITNUMBER(12)
#define                         FLEXCAN_RXIMR2_MI13 BITNUMBER(13)
#define                         FLEXCAN_RXIMR2_MI14 BITNUMBER(14)
#define                         FLEXCAN_RXIMR2_MI15 BITNUMBER(15)
#define                         FLEXCAN_RXIMR2_MI16 BITNUMBER(16)
#define                         FLEXCAN_RXIMR2_MI17 BITNUMBER(17)
#define                         FLEXCAN_RXIMR2_MI18 BITNUMBER(18)
#define                         FLEXCAN_RXIMR2_MI19 BITNUMBER(19)
#define                         FLEXCAN_RXIMR2_MI20 BITNUMBER(20)
#define                         FLEXCAN_RXIMR2_MI21 BITNUMBER(21)
#define                         FLEXCAN_RXIMR2_MI22 BITNUMBER(22)
#define                         FLEXCAN_RXIMR2_MI23 BITNUMBER(23)
#define                         FLEXCAN_RXIMR2_MI24 BITNUMBER(24)
#define                         FLEXCAN_RXIMR2_MI25 BITNUMBER(25)
#define                         FLEXCAN_RXIMR2_MI26 BITNUMBER(26)
#define                         FLEXCAN_RXIMR2_MI27 BITNUMBER(27)
#define                         FLEXCAN_RXIMR2_MI28 BITNUMBER(28)
#define                         FLEXCAN_RXIMR2_MI29 BITNUMBER(29)
#define                         FLEXCAN_RXIMR2_MI30 BITNUMBER(30)
#define                         FLEXCAN_RXIMR2_MI31 BITNUMBER(31)

/* Bit definitions and macros for FLEXCAN_RXIMR3 */
#define                          FLEXCAN_RXIMR3_MI0 BITNUMBER(0)
#define                          FLEXCAN_RXIMR3_MI1 BITNUMBER(1)
#define                          FLEXCAN_RXIMR3_MI2 BITNUMBER(2)
#define                          FLEXCAN_RXIMR3_MI3 BITNUMBER(3)
#define                          FLEXCAN_RXIMR3_MI4 BITNUMBER(4)
#define                          FLEXCAN_RXIMR3_MI5 BITNUMBER(5)
#define                          FLEXCAN_RXIMR3_MI6 BITNUMBER(6)
#define                          FLEXCAN_RXIMR3_MI7 BITNUMBER(7)
#define                          FLEXCAN_RXIMR3_MI8 BITNUMBER(8)
#define                          FLEXCAN_RXIMR3_MI9 BITNUMBER(9)
#define                         FLEXCAN_RXIMR3_MI10 BITNUMBER(10)
#define                         FLEXCAN_RXIMR3_MI11 BITNUMBER(11)
#define                         FLEXCAN_RXIMR3_MI12 BITNUMBER(12)
#define                         FLEXCAN_RXIMR3_MI13 BITNUMBER(13)
#define                         FLEXCAN_RXIMR3_MI14 BITNUMBER(14)
#define                         FLEXCAN_RXIMR3_MI15 BITNUMBER(15)
#define                         FLEXCAN_RXIMR3_MI16 BITNUMBER(16)
#define                         FLEXCAN_RXIMR3_MI17 BITNUMBER(17)
#define                         FLEXCAN_RXIMR3_MI18 BITNUMBER(18)
#define                         FLEXCAN_RXIMR3_MI19 BITNUMBER(19)
#define                         FLEXCAN_RXIMR3_MI20 BITNUMBER(20)
#define                         FLEXCAN_RXIMR3_MI21 BITNUMBER(21)
#define                         FLEXCAN_RXIMR3_MI22 BITNUMBER(22)
#define                         FLEXCAN_RXIMR3_MI23 BITNUMBER(23)
#define                         FLEXCAN_RXIMR3_MI24 BITNUMBER(24)
#define                         FLEXCAN_RXIMR3_MI25 BITNUMBER(25)
#define                         FLEXCAN_RXIMR3_MI26 BITNUMBER(26)
#define                         FLEXCAN_RXIMR3_MI27 BITNUMBER(27)
#define                         FLEXCAN_RXIMR3_MI28 BITNUMBER(28)
#define                         FLEXCAN_RXIMR3_MI29 BITNUMBER(29)
#define                         FLEXCAN_RXIMR3_MI30 BITNUMBER(30)
#define                         FLEXCAN_RXIMR3_MI31 BITNUMBER(31)

/* Bit definitions and macros for FLEXCAN_RXIMR4 */
#define                          FLEXCAN_RXIMR4_MI0 BITNUMBER(0)
#define                          FLEXCAN_RXIMR4_MI1 BITNUMBER(1)
#define                          FLEXCAN_RXIMR4_MI2 BITNUMBER(2)
#define                          FLEXCAN_RXIMR4_MI3 BITNUMBER(3)
#define                          FLEXCAN_RXIMR4_MI4 BITNUMBER(4)
#define                          FLEXCAN_RXIMR4_MI5 BITNUMBER(5)
#define                          FLEXCAN_RXIMR4_MI6 BITNUMBER(6)
#define                          FLEXCAN_RXIMR4_MI7 BITNUMBER(7)
#define                          FLEXCAN_RXIMR4_MI8 BITNUMBER(8)
#define                          FLEXCAN_RXIMR4_MI9 BITNUMBER(9)
#define                         FLEXCAN_RXIMR4_MI10 BITNUMBER(10)
#define                         FLEXCAN_RXIMR4_MI11 BITNUMBER(11)
#define                         FLEXCAN_RXIMR4_MI12 BITNUMBER(12)
#define                         FLEXCAN_RXIMR4_MI13 BITNUMBER(13)
#define                         FLEXCAN_RXIMR4_MI14 BITNUMBER(14)
#define                         FLEXCAN_RXIMR4_MI15 BITNUMBER(15)
#define                         FLEXCAN_RXIMR4_MI16 BITNUMBER(16)
#define                         FLEXCAN_RXIMR4_MI17 BITNUMBER(17)
#define                         FLEXCAN_RXIMR4_MI18 BITNUMBER(18)
#define                         FLEXCAN_RXIMR4_MI19 BITNUMBER(19)
#define                         FLEXCAN_RXIMR4_MI20 BITNUMBER(20)
#define                         FLEXCAN_RXIMR4_MI21 BITNUMBER(21)
#define                         FLEXCAN_RXIMR4_MI22 BITNUMBER(22)
#define                         FLEXCAN_RXIMR4_MI23 BITNUMBER(23)
#define                         FLEXCAN_RXIMR4_MI24 BITNUMBER(24)
#define                         FLEXCAN_RXIMR4_MI25 BITNUMBER(25)
#define                         FLEXCAN_RXIMR4_MI26 BITNUMBER(26)
#define                         FLEXCAN_RXIMR4_MI27 BITNUMBER(27)
#define                         FLEXCAN_RXIMR4_MI28 BITNUMBER(28)
#define                         FLEXCAN_RXIMR4_MI29 BITNUMBER(29)
#define                         FLEXCAN_RXIMR4_MI30 BITNUMBER(30)
#define                         FLEXCAN_RXIMR4_MI31 BITNUMBER(31)

/* Bit definitions and macros for FLEXCAN_RXIMR5 */
#define                          FLEXCAN_RXIMR5_MI0 BITNUMBER(0)
#define                          FLEXCAN_RXIMR5_MI1 BITNUMBER(1)
#define                          FLEXCAN_RXIMR5_MI2 BITNUMBER(2)
#define                          FLEXCAN_RXIMR5_MI3 BITNUMBER(3)
#define                          FLEXCAN_RXIMR5_MI4 BITNUMBER(4)
#define                          FLEXCAN_RXIMR5_MI5 BITNUMBER(5)
#define                          FLEXCAN_RXIMR5_MI6 BITNUMBER(6)
#define                          FLEXCAN_RXIMR5_MI7 BITNUMBER(7)
#define                          FLEXCAN_RXIMR5_MI8 BITNUMBER(8)
#define                          FLEXCAN_RXIMR5_MI9 BITNUMBER(9)
#define                         FLEXCAN_RXIMR5_MI10 BITNUMBER(10)
#define                         FLEXCAN_RXIMR5_MI11 BITNUMBER(11)
#define                         FLEXCAN_RXIMR5_MI12 BITNUMBER(12)
#define                         FLEXCAN_RXIMR5_MI13 BITNUMBER(13)
#define                         FLEXCAN_RXIMR5_MI14 BITNUMBER(14)
#define                         FLEXCAN_RXIMR5_MI15 BITNUMBER(15)
#define                         FLEXCAN_RXIMR5_MI16 BITNUMBER(16)
#define                         FLEXCAN_RXIMR5_MI17 BITNUMBER(17)
#define                         FLEXCAN_RXIMR5_MI18 BITNUMBER(18)
#define                         FLEXCAN_RXIMR5_MI19 BITNUMBER(19)
#define                         FLEXCAN_RXIMR5_MI20 BITNUMBER(20)
#define                         FLEXCAN_RXIMR5_MI21 BITNUMBER(21)
#define                         FLEXCAN_RXIMR5_MI22 BITNUMBER(22)
#define                         FLEXCAN_RXIMR5_MI23 BITNUMBER(23)
#define                         FLEXCAN_RXIMR5_MI24 BITNUMBER(24)
#define                         FLEXCAN_RXIMR5_MI25 BITNUMBER(25)
#define                         FLEXCAN_RXIMR5_MI26 BITNUMBER(26)
#define                         FLEXCAN_RXIMR5_MI27 BITNUMBER(27)
#define                         FLEXCAN_RXIMR5_MI28 BITNUMBER(28)
#define                         FLEXCAN_RXIMR5_MI29 BITNUMBER(29)
#define                         FLEXCAN_RXIMR5_MI30 BITNUMBER(30)
#define                         FLEXCAN_RXIMR5_MI31 BITNUMBER(31)

/* Bit definitions and macros for FLEXCAN_RXIMR6 */
#define                          FLEXCAN_RXIMR6_MI0 BITNUMBER(0)
#define                          FLEXCAN_RXIMR6_MI1 BITNUMBER(1)
#define                          FLEXCAN_RXIMR6_MI2 BITNUMBER(2)
#define                          FLEXCAN_RXIMR6_MI3 BITNUMBER(3)
#define                          FLEXCAN_RXIMR6_MI4 BITNUMBER(4)
#define                          FLEXCAN_RXIMR6_MI5 BITNUMBER(5)
#define                          FLEXCAN_RXIMR6_MI6 BITNUMBER(6)
#define                          FLEXCAN_RXIMR6_MI7 BITNUMBER(7)
#define                          FLEXCAN_RXIMR6_MI8 BITNUMBER(8)
#define                          FLEXCAN_RXIMR6_MI9 BITNUMBER(9)
#define                         FLEXCAN_RXIMR6_MI10 BITNUMBER(10)
#define                         FLEXCAN_RXIMR6_MI11 BITNUMBER(11)
#define                         FLEXCAN_RXIMR6_MI12 BITNUMBER(12)
#define                         FLEXCAN_RXIMR6_MI13 BITNUMBER(13)
#define                         FLEXCAN_RXIMR6_MI14 BITNUMBER(14)
#define                         FLEXCAN_RXIMR6_MI15 BITNUMBER(15)
#define                         FLEXCAN_RXIMR6_MI16 BITNUMBER(16)
#define                         FLEXCAN_RXIMR6_MI17 BITNUMBER(17)
#define                         FLEXCAN_RXIMR6_MI18 BITNUMBER(18)
#define                         FLEXCAN_RXIMR6_MI19 BITNUMBER(19)
#define                         FLEXCAN_RXIMR6_MI20 BITNUMBER(20)
#define                         FLEXCAN_RXIMR6_MI21 BITNUMBER(21)
#define                         FLEXCAN_RXIMR6_MI22 BITNUMBER(22)
#define                         FLEXCAN_RXIMR6_MI23 BITNUMBER(23)
#define                         FLEXCAN_RXIMR6_MI24 BITNUMBER(24)
#define                         FLEXCAN_RXIMR6_MI25 BITNUMBER(25)
#define                         FLEXCAN_RXIMR6_MI26 BITNUMBER(26)
#define                         FLEXCAN_RXIMR6_MI27 BITNUMBER(27)
#define                         FLEXCAN_RXIMR6_MI28 BITNUMBER(28)
#define                         FLEXCAN_RXIMR6_MI29 BITNUMBER(29)
#define                         FLEXCAN_RXIMR6_MI30 BITNUMBER(30)
#define                         FLEXCAN_RXIMR6_MI31 BITNUMBER(31)

/* Bit definitions and macros for FLEXCAN_RXIMR7 */
#define                          FLEXCAN_RXIMR7_MI0 BITNUMBER(0)
#define                          FLEXCAN_RXIMR7_MI1 BITNUMBER(1)
#define                          FLEXCAN_RXIMR7_MI2 BITNUMBER(2)
#define                          FLEXCAN_RXIMR7_MI3 BITNUMBER(3)
#define                          FLEXCAN_RXIMR7_MI4 BITNUMBER(4)
#define                          FLEXCAN_RXIMR7_MI5 BITNUMBER(5)
#define                          FLEXCAN_RXIMR7_MI6 BITNUMBER(6)
#define                          FLEXCAN_RXIMR7_MI7 BITNUMBER(7)
#define                          FLEXCAN_RXIMR7_MI8 BITNUMBER(8)
#define                          FLEXCAN_RXIMR7_MI9 BITNUMBER(9)
#define                         FLEXCAN_RXIMR7_MI10 BITNUMBER(10)
#define                         FLEXCAN_RXIMR7_MI11 BITNUMBER(11)
#define                         FLEXCAN_RXIMR7_MI12 BITNUMBER(12)
#define                         FLEXCAN_RXIMR7_MI13 BITNUMBER(13)
#define                         FLEXCAN_RXIMR7_MI14 BITNUMBER(14)
#define                         FLEXCAN_RXIMR7_MI15 BITNUMBER(15)
#define                         FLEXCAN_RXIMR7_MI16 BITNUMBER(16)
#define                         FLEXCAN_RXIMR7_MI17 BITNUMBER(17)
#define                         FLEXCAN_RXIMR7_MI18 BITNUMBER(18)
#define                         FLEXCAN_RXIMR7_MI19 BITNUMBER(19)
#define                         FLEXCAN_RXIMR7_MI20 BITNUMBER(20)
#define                         FLEXCAN_RXIMR7_MI21 BITNUMBER(21)
#define                         FLEXCAN_RXIMR7_MI22 BITNUMBER(22)
#define                         FLEXCAN_RXIMR7_MI23 BITNUMBER(23)
#define                         FLEXCAN_RXIMR7_MI24 BITNUMBER(24)
#define                         FLEXCAN_RXIMR7_MI25 BITNUMBER(25)
#define                         FLEXCAN_RXIMR7_MI26 BITNUMBER(26)
#define                         FLEXCAN_RXIMR7_MI27 BITNUMBER(27)
#define                         FLEXCAN_RXIMR7_MI28 BITNUMBER(28)
#define                         FLEXCAN_RXIMR7_MI29 BITNUMBER(29)
#define                         FLEXCAN_RXIMR7_MI30 BITNUMBER(30)
#define                         FLEXCAN_RXIMR7_MI31 BITNUMBER(31)

/* Bit definitions and macros for FLEXCAN_RXIMR8 */
#define                          FLEXCAN_RXIMR8_MI0 BITNUMBER(0)
#define                          FLEXCAN_RXIMR8_MI1 BITNUMBER(1)
#define                          FLEXCAN_RXIMR8_MI2 BITNUMBER(2)
#define                          FLEXCAN_RXIMR8_MI3 BITNUMBER(3)
#define                          FLEXCAN_RXIMR8_MI4 BITNUMBER(4)
#define                          FLEXCAN_RXIMR8_MI5 BITNUMBER(5)
#define                          FLEXCAN_RXIMR8_MI6 BITNUMBER(6)
#define                          FLEXCAN_RXIMR8_MI7 BITNUMBER(7)
#define                          FLEXCAN_RXIMR8_MI8 BITNUMBER(8)
#define                          FLEXCAN_RXIMR8_MI9 BITNUMBER(9)
#define                         FLEXCAN_RXIMR8_MI10 BITNUMBER(10)
#define                         FLEXCAN_RXIMR8_MI11 BITNUMBER(11)
#define                         FLEXCAN_RXIMR8_MI12 BITNUMBER(12)
#define                         FLEXCAN_RXIMR8_MI13 BITNUMBER(13)
#define                         FLEXCAN_RXIMR8_MI14 BITNUMBER(14)
#define                         FLEXCAN_RXIMR8_MI15 BITNUMBER(15)
#define                         FLEXCAN_RXIMR8_MI16 BITNUMBER(16)
#define                         FLEXCAN_RXIMR8_MI17 BITNUMBER(17)
#define                         FLEXCAN_RXIMR8_MI18 BITNUMBER(18)
#define                         FLEXCAN_RXIMR8_MI19 BITNUMBER(19)
#define                         FLEXCAN_RXIMR8_MI20 BITNUMBER(20)
#define                         FLEXCAN_RXIMR8_MI21 BITNUMBER(21)
#define                         FLEXCAN_RXIMR8_MI22 BITNUMBER(22)
#define                         FLEXCAN_RXIMR8_MI23 BITNUMBER(23)
#define                         FLEXCAN_RXIMR8_MI24 BITNUMBER(24)
#define                         FLEXCAN_RXIMR8_MI25 BITNUMBER(25)
#define                         FLEXCAN_RXIMR8_MI26 BITNUMBER(26)
#define                         FLEXCAN_RXIMR8_MI27 BITNUMBER(27)
#define                         FLEXCAN_RXIMR8_MI28 BITNUMBER(28)
#define                         FLEXCAN_RXIMR8_MI29 BITNUMBER(29)
#define                         FLEXCAN_RXIMR8_MI30 BITNUMBER(30)
#define                         FLEXCAN_RXIMR8_MI31 BITNUMBER(31)

/* Bit definitions and macros for FLEXCAN_RXIMR9 */
#define                          FLEXCAN_RXIMR9_MI0 BITNUMBER(0)
#define                          FLEXCAN_RXIMR9_MI1 BITNUMBER(1)
#define                          FLEXCAN_RXIMR9_MI2 BITNUMBER(2)
#define                          FLEXCAN_RXIMR9_MI3 BITNUMBER(3)
#define                          FLEXCAN_RXIMR9_MI4 BITNUMBER(4)
#define                          FLEXCAN_RXIMR9_MI5 BITNUMBER(5)
#define                          FLEXCAN_RXIMR9_MI6 BITNUMBER(6)
#define                          FLEXCAN_RXIMR9_MI7 BITNUMBER(7)
#define                          FLEXCAN_RXIMR9_MI8 BITNUMBER(8)
#define                          FLEXCAN_RXIMR9_MI9 BITNUMBER(9)
#define                         FLEXCAN_RXIMR9_MI10 BITNUMBER(10)
#define                         FLEXCAN_RXIMR9_MI11 BITNUMBER(11)
#define                         FLEXCAN_RXIMR9_MI12 BITNUMBER(12)
#define                         FLEXCAN_RXIMR9_MI13 BITNUMBER(13)
#define                         FLEXCAN_RXIMR9_MI14 BITNUMBER(14)
#define                         FLEXCAN_RXIMR9_MI15 BITNUMBER(15)
#define                         FLEXCAN_RXIMR9_MI16 BITNUMBER(16)
#define                         FLEXCAN_RXIMR9_MI17 BITNUMBER(17)
#define                         FLEXCAN_RXIMR9_MI18 BITNUMBER(18)
#define                         FLEXCAN_RXIMR9_MI19 BITNUMBER(19)
#define                         FLEXCAN_RXIMR9_MI20 BITNUMBER(20)
#define                         FLEXCAN_RXIMR9_MI21 BITNUMBER(21)
#define                         FLEXCAN_RXIMR9_MI22 BITNUMBER(22)
#define                         FLEXCAN_RXIMR9_MI23 BITNUMBER(23)
#define                         FLEXCAN_RXIMR9_MI24 BITNUMBER(24)
#define                         FLEXCAN_RXIMR9_MI25 BITNUMBER(25)
#define                         FLEXCAN_RXIMR9_MI26 BITNUMBER(26)
#define                         FLEXCAN_RXIMR9_MI27 BITNUMBER(27)
#define                         FLEXCAN_RXIMR9_MI28 BITNUMBER(28)
#define                         FLEXCAN_RXIMR9_MI29 BITNUMBER(29)
#define                         FLEXCAN_RXIMR9_MI30 BITNUMBER(30)
#define                         FLEXCAN_RXIMR9_MI31 BITNUMBER(31)

/* Bit definitions and macros for FLEXCAN_RXIMR10 */
#define                         FLEXCAN_RXIMR10_MI0 BITNUMBER(0)
#define                         FLEXCAN_RXIMR10_MI1 BITNUMBER(1)
#define                         FLEXCAN_RXIMR10_MI2 BITNUMBER(2)
#define                         FLEXCAN_RXIMR10_MI3 BITNUMBER(3)
#define                         FLEXCAN_RXIMR10_MI4 BITNUMBER(4)
#define                         FLEXCAN_RXIMR10_MI5 BITNUMBER(5)
#define                         FLEXCAN_RXIMR10_MI6 BITNUMBER(6)
#define                         FLEXCAN_RXIMR10_MI7 BITNUMBER(7)
#define                         FLEXCAN_RXIMR10_MI8 BITNUMBER(8)
#define                         FLEXCAN_RXIMR10_MI9 BITNUMBER(9)
#define                        FLEXCAN_RXIMR10_MI10 BITNUMBER(10)
#define                        FLEXCAN_RXIMR10_MI11 BITNUMBER(11)
#define                        FLEXCAN_RXIMR10_MI12 BITNUMBER(12)
#define                        FLEXCAN_RXIMR10_MI13 BITNUMBER(13)
#define                        FLEXCAN_RXIMR10_MI14 BITNUMBER(14)
#define                        FLEXCAN_RXIMR10_MI15 BITNUMBER(15)
#define                        FLEXCAN_RXIMR10_MI16 BITNUMBER(16)
#define                        FLEXCAN_RXIMR10_MI17 BITNUMBER(17)
#define                        FLEXCAN_RXIMR10_MI18 BITNUMBER(18)
#define                        FLEXCAN_RXIMR10_MI19 BITNUMBER(19)
#define                        FLEXCAN_RXIMR10_MI20 BITNUMBER(20)
#define                        FLEXCAN_RXIMR10_MI21 BITNUMBER(21)
#define                        FLEXCAN_RXIMR10_MI22 BITNUMBER(22)
#define                        FLEXCAN_RXIMR10_MI23 BITNUMBER(23)
#define                        FLEXCAN_RXIMR10_MI24 BITNUMBER(24)
#define                        FLEXCAN_RXIMR10_MI25 BITNUMBER(25)
#define                        FLEXCAN_RXIMR10_MI26 BITNUMBER(26)
#define                        FLEXCAN_RXIMR10_MI27 BITNUMBER(27)
#define                        FLEXCAN_RXIMR10_MI28 BITNUMBER(28)
#define                        FLEXCAN_RXIMR10_MI29 BITNUMBER(29)
#define                        FLEXCAN_RXIMR10_MI30 BITNUMBER(30)
#define                        FLEXCAN_RXIMR10_MI31 BITNUMBER(31)

/* Bit definitions and macros for FLEXCAN_RXIMR11 */
#define                         FLEXCAN_RXIMR11_MI0 BITNUMBER(0)
#define                         FLEXCAN_RXIMR11_MI1 BITNUMBER(1)
#define                         FLEXCAN_RXIMR11_MI2 BITNUMBER(2)
#define                         FLEXCAN_RXIMR11_MI3 BITNUMBER(3)
#define                         FLEXCAN_RXIMR11_MI4 BITNUMBER(4)
#define                         FLEXCAN_RXIMR11_MI5 BITNUMBER(5)
#define                         FLEXCAN_RXIMR11_MI6 BITNUMBER(6)
#define                         FLEXCAN_RXIMR11_MI7 BITNUMBER(7)
#define                         FLEXCAN_RXIMR11_MI8 BITNUMBER(8)
#define                         FLEXCAN_RXIMR11_MI9 BITNUMBER(9)
#define                        FLEXCAN_RXIMR11_MI10 BITNUMBER(10)
#define                        FLEXCAN_RXIMR11_MI11 BITNUMBER(11)
#define                        FLEXCAN_RXIMR11_MI12 BITNUMBER(12)
#define                        FLEXCAN_RXIMR11_MI13 BITNUMBER(13)
#define                        FLEXCAN_RXIMR11_MI14 BITNUMBER(14)
#define                        FLEXCAN_RXIMR11_MI15 BITNUMBER(15)
#define                        FLEXCAN_RXIMR11_MI16 BITNUMBER(16)
#define                        FLEXCAN_RXIMR11_MI17 BITNUMBER(17)
#define                        FLEXCAN_RXIMR11_MI18 BITNUMBER(18)
#define                        FLEXCAN_RXIMR11_MI19 BITNUMBER(19)
#define                        FLEXCAN_RXIMR11_MI20 BITNUMBER(20)
#define                        FLEXCAN_RXIMR11_MI21 BITNUMBER(21)
#define                        FLEXCAN_RXIMR11_MI22 BITNUMBER(22)
#define                        FLEXCAN_RXIMR11_MI23 BITNUMBER(23)
#define                        FLEXCAN_RXIMR11_MI24 BITNUMBER(24)
#define                        FLEXCAN_RXIMR11_MI25 BITNUMBER(25)
#define                        FLEXCAN_RXIMR11_MI26 BITNUMBER(26)
#define                        FLEXCAN_RXIMR11_MI27 BITNUMBER(27)
#define                        FLEXCAN_RXIMR11_MI28 BITNUMBER(28)
#define                        FLEXCAN_RXIMR11_MI29 BITNUMBER(29)
#define                        FLEXCAN_RXIMR11_MI30 BITNUMBER(30)
#define                        FLEXCAN_RXIMR11_MI31 BITNUMBER(31)

/* Bit definitions and macros for FLEXCAN_RXIMR12 */
#define                         FLEXCAN_RXIMR12_MI0 BITNUMBER(0)
#define                         FLEXCAN_RXIMR12_MI1 BITNUMBER(1)
#define                         FLEXCAN_RXIMR12_MI2 BITNUMBER(2)
#define                         FLEXCAN_RXIMR12_MI3 BITNUMBER(3)
#define                         FLEXCAN_RXIMR12_MI4 BITNUMBER(4)
#define                         FLEXCAN_RXIMR12_MI5 BITNUMBER(5)
#define                         FLEXCAN_RXIMR12_MI6 BITNUMBER(6)
#define                         FLEXCAN_RXIMR12_MI7 BITNUMBER(7)
#define                         FLEXCAN_RXIMR12_MI8 BITNUMBER(8)
#define                         FLEXCAN_RXIMR12_MI9 BITNUMBER(9)
#define                        FLEXCAN_RXIMR12_MI10 BITNUMBER(10)
#define                        FLEXCAN_RXIMR12_MI11 BITNUMBER(11)
#define                        FLEXCAN_RXIMR12_MI12 BITNUMBER(12)
#define                        FLEXCAN_RXIMR12_MI13 BITNUMBER(13)
#define                        FLEXCAN_RXIMR12_MI14 BITNUMBER(14)
#define                        FLEXCAN_RXIMR12_MI15 BITNUMBER(15)
#define                        FLEXCAN_RXIMR12_MI16 BITNUMBER(16)
#define                        FLEXCAN_RXIMR12_MI17 BITNUMBER(17)
#define                        FLEXCAN_RXIMR12_MI18 BITNUMBER(18)
#define                        FLEXCAN_RXIMR12_MI19 BITNUMBER(19)
#define                        FLEXCAN_RXIMR12_MI20 BITNUMBER(20)
#define                        FLEXCAN_RXIMR12_MI21 BITNUMBER(21)
#define                        FLEXCAN_RXIMR12_MI22 BITNUMBER(22)
#define                        FLEXCAN_RXIMR12_MI23 BITNUMBER(23)
#define                        FLEXCAN_RXIMR12_MI24 BITNUMBER(24)
#define                        FLEXCAN_RXIMR12_MI25 BITNUMBER(25)
#define                        FLEXCAN_RXIMR12_MI26 BITNUMBER(26)
#define                        FLEXCAN_RXIMR12_MI27 BITNUMBER(27)
#define                        FLEXCAN_RXIMR12_MI28 BITNUMBER(28)
#define                        FLEXCAN_RXIMR12_MI29 BITNUMBER(29)
#define                        FLEXCAN_RXIMR12_MI30 BITNUMBER(30)
#define                        FLEXCAN_RXIMR12_MI31 BITNUMBER(31)

/* Bit definitions and macros for FLEXCAN_RXIMR13 */
#define                         FLEXCAN_RXIMR13_MI0 BITNUMBER(0)
#define                         FLEXCAN_RXIMR13_MI1 BITNUMBER(1)
#define                         FLEXCAN_RXIMR13_MI2 BITNUMBER(2)
#define                         FLEXCAN_RXIMR13_MI3 BITNUMBER(3)
#define                         FLEXCAN_RXIMR13_MI4 BITNUMBER(4)
#define                         FLEXCAN_RXIMR13_MI5 BITNUMBER(5)
#define                         FLEXCAN_RXIMR13_MI6 BITNUMBER(6)
#define                         FLEXCAN_RXIMR13_MI7 BITNUMBER(7)
#define                         FLEXCAN_RXIMR13_MI8 BITNUMBER(8)
#define                         FLEXCAN_RXIMR13_MI9 BITNUMBER(9)
#define                        FLEXCAN_RXIMR13_MI10 BITNUMBER(10)
#define                        FLEXCAN_RXIMR13_MI11 BITNUMBER(11)
#define                        FLEXCAN_RXIMR13_MI12 BITNUMBER(12)
#define                        FLEXCAN_RXIMR13_MI13 BITNUMBER(13)
#define                        FLEXCAN_RXIMR13_MI14 BITNUMBER(14)
#define                        FLEXCAN_RXIMR13_MI15 BITNUMBER(15)
#define                        FLEXCAN_RXIMR13_MI16 BITNUMBER(16)
#define                        FLEXCAN_RXIMR13_MI17 BITNUMBER(17)
#define                        FLEXCAN_RXIMR13_MI18 BITNUMBER(18)
#define                        FLEXCAN_RXIMR13_MI19 BITNUMBER(19)
#define                        FLEXCAN_RXIMR13_MI20 BITNUMBER(20)
#define                        FLEXCAN_RXIMR13_MI21 BITNUMBER(21)
#define                        FLEXCAN_RXIMR13_MI22 BITNUMBER(22)
#define                        FLEXCAN_RXIMR13_MI23 BITNUMBER(23)
#define                        FLEXCAN_RXIMR13_MI24 BITNUMBER(24)
#define                        FLEXCAN_RXIMR13_MI25 BITNUMBER(25)
#define                        FLEXCAN_RXIMR13_MI26 BITNUMBER(26)
#define                        FLEXCAN_RXIMR13_MI27 BITNUMBER(27)
#define                        FLEXCAN_RXIMR13_MI28 BITNUMBER(28)
#define                        FLEXCAN_RXIMR13_MI29 BITNUMBER(29)
#define                        FLEXCAN_RXIMR13_MI30 BITNUMBER(30)
#define                        FLEXCAN_RXIMR13_MI31 BITNUMBER(31)

/* Bit definitions and macros for FLEXCAN_RXIMR14 */
#define                         FLEXCAN_RXIMR14_MI0 BITNUMBER(0)
#define                         FLEXCAN_RXIMR14_MI1 BITNUMBER(1)
#define                         FLEXCAN_RXIMR14_MI2 BITNUMBER(2)
#define                         FLEXCAN_RXIMR14_MI3 BITNUMBER(3)
#define                         FLEXCAN_RXIMR14_MI4 BITNUMBER(4)
#define                         FLEXCAN_RXIMR14_MI5 BITNUMBER(5)
#define                         FLEXCAN_RXIMR14_MI6 BITNUMBER(6)
#define                         FLEXCAN_RXIMR14_MI7 BITNUMBER(7)
#define                         FLEXCAN_RXIMR14_MI8 BITNUMBER(8)
#define                         FLEXCAN_RXIMR14_MI9 BITNUMBER(9)
#define                        FLEXCAN_RXIMR14_MI10 BITNUMBER(10)
#define                        FLEXCAN_RXIMR14_MI11 BITNUMBER(11)
#define                        FLEXCAN_RXIMR14_MI12 BITNUMBER(12)
#define                        FLEXCAN_RXIMR14_MI13 BITNUMBER(13)
#define                        FLEXCAN_RXIMR14_MI14 BITNUMBER(14)
#define                        FLEXCAN_RXIMR14_MI15 BITNUMBER(15)
#define                        FLEXCAN_RXIMR14_MI16 BITNUMBER(16)
#define                        FLEXCAN_RXIMR14_MI17 BITNUMBER(17)
#define                        FLEXCAN_RXIMR14_MI18 BITNUMBER(18)
#define                        FLEXCAN_RXIMR14_MI19 BITNUMBER(19)
#define                        FLEXCAN_RXIMR14_MI20 BITNUMBER(20)
#define                        FLEXCAN_RXIMR14_MI21 BITNUMBER(21)
#define                        FLEXCAN_RXIMR14_MI22 BITNUMBER(22)
#define                        FLEXCAN_RXIMR14_MI23 BITNUMBER(23)
#define                        FLEXCAN_RXIMR14_MI24 BITNUMBER(24)
#define                        FLEXCAN_RXIMR14_MI25 BITNUMBER(25)
#define                        FLEXCAN_RXIMR14_MI26 BITNUMBER(26)
#define                        FLEXCAN_RXIMR14_MI27 BITNUMBER(27)
#define                        FLEXCAN_RXIMR14_MI28 BITNUMBER(28)
#define                        FLEXCAN_RXIMR14_MI29 BITNUMBER(29)
#define                        FLEXCAN_RXIMR14_MI30 BITNUMBER(30)
#define                        FLEXCAN_RXIMR14_MI31 BITNUMBER(31)

/* Bit definitions and macros for FLEXCAN_RXIMR15 */
#define                         FLEXCAN_RXIMR15_MI0 BITNUMBER(0)
#define                         FLEXCAN_RXIMR15_MI1 BITNUMBER(1)
#define                         FLEXCAN_RXIMR15_MI2 BITNUMBER(2)
#define                         FLEXCAN_RXIMR15_MI3 BITNUMBER(3)
#define                         FLEXCAN_RXIMR15_MI4 BITNUMBER(4)
#define                         FLEXCAN_RXIMR15_MI5 BITNUMBER(5)
#define                         FLEXCAN_RXIMR15_MI6 BITNUMBER(6)
#define                         FLEXCAN_RXIMR15_MI7 BITNUMBER(7)
#define                         FLEXCAN_RXIMR15_MI8 BITNUMBER(8)
#define                         FLEXCAN_RXIMR15_MI9 BITNUMBER(9)
#define                        FLEXCAN_RXIMR15_MI10 BITNUMBER(10)
#define                        FLEXCAN_RXIMR15_MI11 BITNUMBER(11)
#define                        FLEXCAN_RXIMR15_MI12 BITNUMBER(12)
#define                        FLEXCAN_RXIMR15_MI13 BITNUMBER(13)
#define                        FLEXCAN_RXIMR15_MI14 BITNUMBER(14)
#define                        FLEXCAN_RXIMR15_MI15 BITNUMBER(15)
#define                        FLEXCAN_RXIMR15_MI16 BITNUMBER(16)
#define                        FLEXCAN_RXIMR15_MI17 BITNUMBER(17)
#define                        FLEXCAN_RXIMR15_MI18 BITNUMBER(18)
#define                        FLEXCAN_RXIMR15_MI19 BITNUMBER(19)
#define                        FLEXCAN_RXIMR15_MI20 BITNUMBER(20)
#define                        FLEXCAN_RXIMR15_MI21 BITNUMBER(21)
#define                        FLEXCAN_RXIMR15_MI22 BITNUMBER(22)
#define                        FLEXCAN_RXIMR15_MI23 BITNUMBER(23)
#define                        FLEXCAN_RXIMR15_MI24 BITNUMBER(24)
#define                        FLEXCAN_RXIMR15_MI25 BITNUMBER(25)
#define                        FLEXCAN_RXIMR15_MI26 BITNUMBER(26)
#define                        FLEXCAN_RXIMR15_MI27 BITNUMBER(27)
#define                        FLEXCAN_RXIMR15_MI28 BITNUMBER(28)
#define                        FLEXCAN_RXIMR15_MI29 BITNUMBER(29)
#define                        FLEXCAN_RXIMR15_MI30 BITNUMBER(30)
#define                        FLEXCAN_RXIMR15_MI31 BITNUMBER(31)

/* Bit definitions for CRC register */
#define                   FLEXCAN_CRCR_MBCRC_BIT_NO (16)
#define                     FLEXCAN_CRCR_MBCRC_MASK (0x007F0000LU)
#define                     FLEXCAN_CRCR_CRC_BIT_NO (0)
#define                       FLEXCAN_CRCR_CRC_MASK (0x00007FFFLU)

/* Bit definition for Individual Matching Elements Update Register (IMEUR) */
#define                    FLEXCAN_IMEUR_IMEUP_MASK (0x0000007FLU)
#define                  FLEXCAN_IMEUR_IMEUP_BIT_NO (0)
#define                  FLEXCAN_IMEUR_IMEUREQ_MASK BITNUMBER(8)
#define                  FLEXCAN_IMEUR_IMEUACK_MASK BITNUMBER(9)
#define              FLEXCAN_Set_IMEUP(imeur,imeup) imeur = (imeur & ~(FLEXCAN_IMEUR_IMEUP_MASK)) | (imeup & FLEXCAN_IMEUR_IMEUP_MASK)
#define                    FLEXCAN_Get_IMEUP(imeur) (imeur & FLEXCAN_IMEUR_IMEUP_MASK)

/* Bit definition for Lost Rx Frames Register (LRFR)
 */
#define                   FLEXCAN_LRFR_LOSTRLP_MASK (0x007F0000LU)
#define                  FLEXCAN_LRFR_LFIFOMTC_MASK BITNUMBER(15)
#define                   FLEXCAN_LRFR_LOSTRMP_MASK (0x000001FFLU)
#define                 FLEXCAN_LRFR_LOSTRLP_BIT_NO (16)
#define                FLEXCAN_LRFR_LFIFOMTC_BIT_NO (15)
#define                 FLEXCAN_LRFR_LOSTRMP_BIT_NO (0)
#define              FLEXCAN_Get_LostMBLocked(lrfr) ((lrfr & FLEXCAN_LRFR_LOSTRLP_MASK)>>(FLEXCAN_LRFR_LOSTRLP_BIT_NO))
#define             FLEXCAN_Get_LostMBUpdated(lrfr) ((lrfr & FLEXCAN_LRFR_LOSTRMP_MASK))

/* Bit definition for Memory Error Control Register */
#define                  FLEXCAN_MECR_NCEFAFRZ_MASK BITNUMBER(7)
#define                   FLEXCAN_MECR_RERRDIS_MASK BITNUMBER(8)
#define                  FLEXCAN_MECR_EXTERRIE_MAKS BITNUMBER(13)
#define                   FLEXCAN_MECR_FAERRIE_MAKS BITNUMBER(14)
#define                   FLEXCAN_MECR_HAERRIE_MAKS BITNUMBER(15)
#define                   FLEXCAN_MECR_CEI_MSK_MAKS BITNUMBER(16)
#define                FLEXCAN_MECR_FANCEI_MSK_MAKS BITNUMBER(18)
#define                FLEXCAN_MECR_HANCEI_MSK_MAKS BITNUMBER(19)
#define              FLEXCAN_MECR_ECRWRDIS_MSK_MAKS BITNUMBER(31)

/* Bit definition for Error Report Address Register (RERRAR) */
#define                     FLEXCAN_RERRAR_NCE_MASK BITNUMBER(24)
#define                    FLEXCAN_RERRAR_SAID_MASK (0x00070000LU)
#define                        FLEXCAN_ERRADDR_MASK (0x00003FFFLU)

/* Bit definition for Error Report Syndrome Register (RERRSYNR) */
#define                   FLEXCAN_RERRSYNR_BE3_MASK BITNUMBER(31)
#define                 FLEXCAN_RERRSYNR_SYND3_MASK (0x1F000000LU)
#define               FLEXCAN_RERRSYNR_SYND3_BIT_NO (24)
#define                   FLEXCAN_RERRSYNR_BE2_MASK BITNUMBER(23)
#define                 FLEXCAN_RERRSYNR_SYND2_MASK (0x001F0000LU)
#define               FLEXCAN_RERRSYNR_SYND2_BIT_NO (16)
#define                   FLEXCAN_RERRSYNR_BE1_MASK BITNUMBER(15)
#define                 FLEXCAN_RERRSYNR_SYND1_MASK (0x00001F00LU)
#define               FLEXCAN_RERRSYNR_SYND1_BIT_NO (8)
#define                   FLEXCAN_RERRSYNR_BE0_MASK BITNUMBER(7)
#define                 FLEXCAN_RERRSYNR_SYND0_MASK (0x0000001FLU)
#define               FLEXCAN_RERRSYNR_SYND0_BIT_NO (0)

#define   FLEXCAN_RERRSYNR_check_BEn_Bit(errsynr,n) (errsynr & FLEXCAN_RERRSYNR_BE##n##_MASK)
#define       FLEXCAN_RERRSYNR_get_SYNDn(errsynr,n) (errsynr & FLEXCAN_RERRSYNR_SYND##n##_MASK)
#define FLEXCAN_RERRSYNR_check_SYNDn_Bit(errsynr,n) ((errsynr & FLEXCAN_RERRSYNR_SYND##n##_MASK)>>FLEXCAN_RERRSYNR_SYND##n##_BIT_NO)

/* Bit definition for Error Status Register (ERRSR) */
#define                    FLEXCAN_ERRSR_CEIOF_MASK BITNUMBER(0)
#define                 FLEXCAN_ERRSR_FANCEIOF_MASK BITNUMBER(2)
#define                 FLEXCAN_ERRSR_HANCEIOF_MASK BITNUMBER(3)
#define                     FLEXCAN_ERRSR_CEIF_MASK BITNUMBER(16)
#define                  FLEXCAN_ERRSR_FANCEIF_MASK BITNUMBER(18)
#define                  FLEXCAN_ERRSR_HANCEIF_MASK BITNUMBER(19)

// Allow different xtal usage
#if !defined(F_CAN)
#if !defined(FLEXCAN_BASE_FREQ)
#define FLEXCAN_BASE_FREQ 16000000
#define FLEXCANb_CTRL1_SETUP(x) FLEXCANb_CTRL1(x) &= ~FLEXCAN_CTRL_CLK_SRC
#endif
#else
// Allow alternate clock path and frequency.
#define FLEXCAN_BASE_FREQ F_CAN
#if !defined(XTAL_F)
#define FLEXCANb_CTRL1_SETUP(x) FLEXCANb_CTRL1(x) |= FLEXCAN_CTRL_CLK_SRC;
#endif
#endif


/********************************************************************/
#endif // __KINETIS_FLEXCAN_H
